[package]
name = "tcpexample"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tcplistener"
path = "src/bin/tcplistener.rs"

[[bin]]
name = "tcpsender"
path = "src/bin/tcpsender.rs"


[dependencies]
