[package]
name = "tcpexample"
version = "0.1.0"
edition = "2024"

[lib]
name = "tcpexample"
path = "src/lib.rs"

[[bin]]
name = "tcplistener"
path = "src/bin/tcplistener.rs"

[[bin]]
name = "tcpsender"
path = "src/bin/tcpsender.rs"


[dependencies]
bincode = "2.0.1"
chrono = "0.4.40"
